### ISSUE TITLE
The cooldowns for the assault rifle and melee attack aren't shared.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#10]
If the player shoots, he can melee right after.

![image](https://cloud.githubusercontent.com/assets/11168751/10090074/ed9ca808-62f8-11e5-876b-5255bbfab1be.png)

**Comment by symbol24** [comment]
also fixed the shooting and melee ignoring cooldowns almost totally lol...

**Comment by jeffcerto** [comment]
Checked and fixed
