### ISSUE TITLE
Return to main menu brings a black screen

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#101]
![image](https://cloud.githubusercontent.com/assets/11168751/10652606/0cf66c4c-7826-11e5-9901-a2215fc11337.png)

**Comment by jeffcerto** [comment]
Comment : when in the final round menu, it doesnt happen. only while in game and if you press pause

**Comment by BenGoulet** [comment]
I believe that's the issue you showed us that Phil said wasn't a problem? If you can repro using Build & Run, though, it's a problem.

**Comment by jeffcerto** [comment]
yes I reproduced it in the build and run

**Comment by BenGoulet** [comment]
Probably linked with https://github.com/symbol24/ProjectJuice/issues/127 now.

**Comment by symbol24** [comment]
The time scale was not being reset, and thus, remaining on a black screen, our a white screen with new loading. tell me if you find a way to repro this, it should be very solid now.

**Comment by jeffcerto** [comment]
checked and fixed
