### ISSUE TITLE
If you dash then jump right after, you can only jump upwards

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#103]

**Comment by symbol24** [comment]
i dont know what you mean, when i dash then jump, i jump up.

**Comment by BenGoulet** [comment]
Reopened.
The idea is you have to keep pressing to the side after/during the dash and try to jump sideways; the jump will be completely vertical instead.

**Comment by symbol24** [comment]
This is how our umping works, its an impulse up, cant change that at this point. WNF

**Comment by BenGoulet** [comment]
That's fine, but I'll want to show you the behavior tomorrow so I'm sure we're on the same page. I understand the limitation, though.

**Comment by symbol24** [comment]
I understand, you dash forward and then you jump vertically halting the forward momentum.

**Comment by BenGoulet** [comment]
Let's WNF it.

**Comment by BenGoulet** [comment]
Reopened with Phil's blessing.

**Comment by jeffcerto** [comment]
checked and fixed
