### ISSUE TITLE
The right player has a dark background (I dont know how to reproduce it)

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#104]
![image](https://cloud.githubusercontent.com/assets/11168751/10652869/0f7f56a2-7828-11e5-8576-6a122661d14d.png)

**Comment by symbol24** [comment]
this is to show that you cannot take the same sponsor as another player, but i dont reset it after haha

**Comment by symbol24** [comment]
no more dark background, the word taken appears on the logo when you cant take it, and disappears if you can.

**Comment by jeffcerto** [comment]
Checked and Fixed.
