### ISSUE TITLE
Barrels sometimes never stop moving and constantly play the sound when pushing them

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#106]
When the player pushes barrels, or a barrel falls from a platform, he will notice they will sometimes never actually rest, start vibrating and constantly play the sound of barrels being pushed.

**Comment by monstervictor** [comment]
After playing with the barrel and trying different things, it would be easier to change the collider overlapping differences than fixing the vibrating issue. I added slippery sides to the barrel anyways like the barrel

**Comment by jeffcerto** [comment]
checked and fixed
