### ISSUE TITLE
Pushing Crates and barrels never triggers the sound for pushing crates

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#107]
The 'Being pushed SFX' of the Non-Explosive Cube does not seem to ever play when pushing crates around.

I've attempted changing the sound to the sound of pushing barrels, in case the sound was the issue, but I still could not hear anything.

EDIT: Currently, both the barrels and crates have stopped outputting sounds when pushed, even though they play their other sounds right.

**Comment by monstervictor** [comment]
Is this bug the same as this? 
https://github.com/symbol24/ProjectJuice/issues/108

**Comment by BenGoulet** [comment]
Marking it as fixed to check it in-game again.

**Comment by BenGoulet** [comment]
Reopened and updated.

**Comment by monstervictor** [comment]
The crate makes sound, but it is not loud enough for the music

**Comment by jeffcerto** [comment]
checked and fixed
