### ISSUE TITLE
Crates & Barrels: Only the beginning of the sounds of pushing them ever plays

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#108]
This is being entered while only barrels currently show this behavior, since crates don't make any sound at the moment, but it seems likely it would occur for them, too.

When the player pushes barrels and crates around and it triggers the sound for pushing them around, he will notice only the very start of the sound will play and repeat very fast.

The expected behavior would be to play the entire sound in loop as long as the crate has momentum.

**Comment by monstervictor** [comment]
This is fixed, the sound effects and delay for spawning particles and playing sounds are configurable.
![sparkingmovementfix](https://cloud.githubusercontent.com/assets/3688151/10681287/a4e4de4c-78f5-11e5-98b0-393c98b66fbb.PNG)

**Comment by jeffcerto** [comment]
fixed
