### ISSUE TITLE
Player gets stuck on crates (while dashing)

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#109]
![image](https://cloud.githubusercontent.com/assets/11168751/10653637/5f28fd3c-782f-11e5-8209-492221e67fbf.png)

**Comment by monstervictor** [comment]
There were 2 problems to this:
Collision placement (that was corrected in the player)
Crates were not slippery on the sides and you could get stuck on the crate. This has been corrected through script

**Comment by jeffcerto** [comment]
checked and fixed
