### ISSUE TITLE
No feedback when ready to shoot or melee

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#114]

**Comment by monstervictor** [comment]
![sappingdartreloadsfx](https://cloud.githubusercontent.com/assets/3688151/10681178/9c565432-78f4-11e5-860e-d65022d5f642.PNG)
Added the new sfx. It will be added when pushing.

**Comment by jeffcerto** [comment]
Gun Reloaded SFX doesnt play, even with any other sound FX

**Comment by symbol24** [comment]
added sounds for melee and shooting reloads

**Comment by symbol24** [comment]
![feedback](https://cloud.githubusercontent.com/assets/9352028/11107643/dd0272f4-88ad-11e5-8729-f489cbee4aea.png)

you can change how many flashes and how long they last as well as setting a color to it. have fun!

**Comment by symbol24** [comment]
it was intigrated for gun, melee and shield. for dart, waiting on new version from victor to intigrate it there. you can create a new bug for that.

**Comment by jeffcerto** [comment]
checked and true
