### ISSUE TITLE
Layer for the dust/smoke from pushing the barrel should be in back of all

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#115]
![image](https://cloud.githubusercontent.com/assets/11168751/10654673/786a6a90-783b-11e5-95ed-d70fac6d8579.png)

**Comment by monstervictor** [comment]
![particlesystemorderlayer](https://cloud.githubusercontent.com/assets/3688151/10680261/1147ff10-78ec-11e5-8653-5eb6300b3fa7.PNG)
This should help. We will do it while adding the right particles.

**Comment by symbol24** [comment]
all particles are being set to the sorting layer Particles and will be in front of all.
