### ISSUE TITLE
Player can jump infinite amount of times only on RIGHT walls

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#117]
![image](https://cloud.githubusercontent.com/assets/11168751/10681697/48ebabc0-78fa-11e5-8c6c-2b97d7d30624.png)

**Comment by jeffcerto** [comment]
Extra comment : only happens when both players are against the walls

**Comment by jeffcerto** [comment]
Extra Extra comment : It can happen without the need of a second player, When the player jumps next to a wall (only while facing right for some reason). He will jump infinite number of times.

**Comment by symbol24** [comment]
fixed a while ago

**Comment by jeffcerto** [comment]
Checked and fixed
