### ISSUE TITLE
When shot the Juice doesn't spray in the direction the player has been hit from

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#12]
![image](https://cloud.githubusercontent.com/assets/11168751/10090144/b573bd3a-62f9-11e5-95d2-1e15bdd2973a.png)

**Comment by jeffcerto** [comment]
When hit with a melee attack: The Juice will spray in the opposite direction the player has been

hit from with moderate to high force. (if hit from the front, the Juice will spray from his back) <--- same here, sometimes goes left or right

**Comment by jeffcerto** [comment]
If the player touches Juice that is being splashed and hasn’t touched the ground yet, he will

collect it immediately. <--- Player doesnt pick it up

**Comment by jeffcerto** [comment]
Sometime the "juice" is stuck in the walls of floors, and it is unreachable by the player

**Comment by monstervictor** [comment]
This should have been fixed with the bullet slowdown.

**Comment by jeffcerto** [comment]
checked and fixed
