### ISSUE TITLE
Muzzle flashes are always displayed sideways

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#121]
When the player fires his weapon, he will notice muzzle flashes coming out of it.
However, when the player is aiming up or down, he will notice the muzzle flashes will be displayed sideways instead of facing up or down.

![image](https://cloud.githubusercontent.com/assets/10607010/10899465/cb45f9b2-81a2-11e5-8a7c-1fb50c4d7a38.png)

**Comment by symbol24** [comment]
new muzzle flash is up for arc gun, need to set it up when we get muzzle for shield

**Comment by jeffcerto** [comment]
checked and fixed
