### ISSUE TITLE
The 'Audio Clip on Go' sound plays too early

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#124]
Tested in engine.

When the player starts a new round, he will notice the Round Start Timer script's 'Audio Clip on Go' will play well before the 'GO!' text appears on the Jumbotron.

**Comment by symbol24** [comment]
the timers were fixed, the sounds are supposed to occur when the purple is at its smallest.

**Comment by BenGoulet** [comment]
Seems fixed.
