### ISSUE TITLE
Player should be able to set a different damage value for the Aerial Battle Axe hit

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#125]
In the Database Object, the player will notice he can modify the values for the regular melee attack and the Battle Axe attack.

However, as we want the GROUNDED Battle Axe to be a one shot kill, we would need to be able to give the AERIAL Battle Axe attack a different damage value, otherwise it will render the Grounded Battle Axe pointless.

![image](https://cloud.githubusercontent.com/assets/10607010/10925649/ecc26e7a-825d-11e5-9823-dfeedf88a0b6.png)

**Comment by symbol24** [comment]
in the databse object just under thatm you have aerial damage. on the melee script on the player, you can choose to use the aerial damage or not, by default it is set to use it.

**Comment by jeffcerto** [comment]
checked and truthified
