### ISSUE TITLE
Battle Axe Ability isn't hitting objects

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#126]
I was able to reproduce this when the player hit one of the crates or barrels before trying to hit another player. (he also wasn't able to hit the other barrels and crates)

![image](https://cloud.githubusercontent.com/assets/11168751/10925690/54c09fc4-825e-11e5-88a7-3b71514a85f8.png)

**Comment by symbol24** [comment]
Try and find better steps to reproduce this

**Comment by BenGoulet** [comment]
I think that got fixed sometime this week. I'll retest before closing, though.

**Comment by BenGoulet** [comment]
Seems fixed.
