### ISSUE TITLE
Vibrations are not on the correct controller

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#128]
Tested with two players.

When both players spawn in-game, they will notice their controllers' vibrations are inverted; Player 1's vibrations are felt in controller 2 and vice versa.

**Comment by monstervictor** [comment]
Using another library for input, we can roll back swapping a script if things go wrong. We will see if the problem reproduces

**Comment by jeffcerto** [comment]
checked and fixed
