### ISSUE TITLE
Health bars' colors are washed out

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#129]
All the players have their health bars shown behind them, it is shown in their Juice's color.

However, the colors look less vibrant, more washed out than they should be.
Phil knows the reason; something about a white background.

![image](https://cloud.githubusercontent.com/assets/10607010/10956174/7b171bf2-8327-11e5-965b-eb246bdcc229.png)

**Comment by jeffcerto** [comment]
checked and fixed
