### ISSUE TITLE
Bullets are sometimes going through other players

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#13]
Sometimes the player shoots bullets to another player, and for some reason it just goes right through

![image](https://cloud.githubusercontent.com/assets/11168751/10090158/00645aa2-62fa-11e5-97a2-5fb5d3638487.png)

**Comment by symbol24** [comment]
i seem to have fixed this by slowing down bullets and increasing their size and collider

**Comment by jeffcerto** [comment]
checked and fixed
