### ISSUE TITLE
Player can no longer turn around after using the grounded Battle Axe

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#130]
When the player uses the Battle Axe, his facing direction is locked, as per design.

However, he will often notice that after the Grounded Battle Axe animation is completed, his character will continue facing in the same direction indefinitely.

![image](https://cloud.githubusercontent.com/assets/10607010/10956439/ba1c6bf2-8329-11e5-9b9a-d7dcf28d92e4.png)

**Comment by jeffcerto** [comment]
when land, cancel aerial

**Comment by symbol24** [comment]
FIXED

**Comment by jeffcerto** [comment]
seems fixed and check by moi
