### ISSUE TITLE
Menus sliding from the top of the screen don't correctly slide in and out of the screen

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#131]
When the pause and end of round/match screens appear and disappear, the player will notice they don't properly enter and leave the top of the screen.

Instead of sliding in from the top, they will suddenly spawn near the top of the screen, stay frozen there briefly and then slide all the way down. When they slide out, the opposite occurs; the menu will not completely go off-screen, stop at the top of the screen and only then disappear.

![image](https://github-cloud.s3.amazonaws.com/assets%2F10607010%2F10957200%2F1b9c1df4-8330-11e5-8a64-23f9d5970318.png)

**Comment by symbol24** [comment]
i think i fixed that when i had to update the menu for the camera size.

**Comment by BenGoulet** [comment]
Seems fixed!
