### ISSUE TITLE
Sapping Wire often auto-cancels itself when hitting an opponent

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#132]
If often happens when shooting the Sapping Wire at an opponent that the Wire will simply cancel itself and not suck any Juice at the moment where it would make contact with the enemy.

**Comment by BenGoulet** [comment]
Although it doesn't auto cancel if both players stay absolutely static, as soon as anyone moves a little, the rope breaks itself almost immediately, making it impossible to use in a real game situation.

**Comment by monstervictor** [comment]
Changed a few parameters in the dart and now it should work better.

**Comment by monstervictor** [comment]
![20151126 dartsettings](https://cloud.githubusercontent.com/assets/3688151/11432520/2a344a08-947e-11e5-8438-10d08da353ad.JPG)

Adding as reference

**Comment by symbol24** [comment]
Since I was in the player prefab I updated with the values and it appears to work great now ^^

**Comment by BenGoulet** [comment]
Keeping an eye on it since it was not working on Jeff's computer in an .exe.

**Comment by BenGoulet** [comment]
Fixed for most computers.
WNF for Jeff's computer.
