### ISSUE TITLE
When players kill each other in a delay, screen says round is draw, but 1 player still gets a medal

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#133]
We both had low lives,  fired my weapon first, then he fired his weapon a split second after me. In the end the medal was awarded to me because I killed him first, but he also killed me after firing his weapon, so winner is draw but player 1 got a medal, player 2 didnt

**Comment by symbol24** [comment]
See #149 as it has the right info.

**Comment by symbol24** [comment]
i couldnt validate, but it should be fixed (dont test with shield as of yet)

**Comment by BenGoulet** [comment]
With the 0.5 seconds delay, it is possible to get a slightly delayed death, trigger a draw and not award anyone medals.
