### ISSUE TITLE
Shooting the sapping wire directly on the ceiling or the floor sometimes makes the game lag

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#134]
Probably because the dart goes through the ceiling

Also you can have an easier time reproducing it if you are far away from the ceiling or the floor.

Example here (player shooting the sapping dart downwards on the floor)

![image](https://cloud.githubusercontent.com/assets/11168751/10985852/ca41d778-83f2-11e5-945f-3d3aaf631fb7.png)

**Comment by BenGoulet** [comment]
Can't seem to reproduce now.
