### ISSUE TITLE
Knifing somone facing the other way still hits the opponent.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#135]
player left is knifing towards the left, and will still hit the player on the right

![image](https://cloud.githubusercontent.com/assets/11168751/10985989/f93c6858-83f3-11e5-942c-762802f8a4a8.png)

**Comment by symbol24** [comment]
swing updated, should be better now

**Comment by BenGoulet** [comment]
Still occurs if the two maimframes are back to back.
Does not occur anymore if they are facing the same direction.

**Comment by BenGoulet** [comment]
As an added note that seems related: The range of the knife when facing right is smaller than it looks, and the range of the knife when facing left is larger than it looks.

**Comment by symbol24** [comment]
at this point is is too minor. ima WNF this.

**Comment by symbol24** [comment]
And now we saw you cant do it anymore, ha!

**Comment by BenGoulet** [comment]
Indeed. No longer possible.
