### ISSUE TITLE
Hit box of melee attacks are not deactivated once they have connected

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#137]
When the player uses the Battle Axe or regular melee attack, he will notice that it is possible for the attacks to hit more than once, instead of hitting once and then deactivating their hit box.

How to reproduce:

With regular melee, hug another player, then turn around to face away from him. Perform the melee attack so as to hit the player with the knife at the very end of the animation, when the knife is behind you; the attack will hit twice.

With Battle Axe: Player A has the Battle Axe, Player B has the Juice Shield. Have Player B shield the Battle Axe attack; notice he will instantly have a fully charged shield.

**Comment by symbol24** [comment]
So theres a bug in unity that sometimes trigger collider will register more than once, i found tons of people complaining about this on line. for the normal melee, changing the animation seems to have removed the issue, and for the battle axe, it was only a real problem on the shield, and I found a solution that works.

**Comment by jeffcerto** [comment]
checked and fixed
