### ISSUE TITLE
Regular Melee attacks do not charge the Juice Shield

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#138]
When the player gets hit with a regular melee attack while he has the Shield up, he will notice that, although he takes no damage, the melee attack will never actually hit him, which prevents the shield from absorbing the damage.

**Comment by symbol24** [comment]
it was not colliding at all with the shield, so no clashing sound either

**Comment by jeffcerto** [comment]
checked and fixed
