### ISSUE TITLE
Player gets stuck while being on top of the other player.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#14]
Sometimes the player gets stuck while being on top of the other player, and he cant move. The only way the player can move again would be for the player that is under moves left or right or jumps

![image](https://cloud.githubusercontent.com/assets/11168751/10090195/7a1e9b6e-62fa-11e5-9be5-a27c0727272b.png)

**Comment by jeffcerto** [comment]
If the player dashes on top of the player, that is when he will get stuck. Much like the crate problem we had

**Comment by symbol24** [comment]
fixed!

**Comment by jeffcerto** [comment]
checked and fixed
