### ISSUE TITLE
Melee Clash vibration is very light / barely noticeable

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#140]
Even though the player sets the values for the melee clash vibrations very high and lengthy, he will notice that the actual clash's vibrations will be very low and short, for both players.

I'm not sure why this occurs.

**Comment by monstervictor** [comment]
PlayerVibrator.cs will take prioratize  harder vibraciones ;)

**Comment by monstervictor** [comment]
Finally Fixed! I will be pushing sooon

**Comment by BenGoulet** [comment]
Can be felt now.

**Comment by BenGoulet** [comment]
It is fixed for a clash between regular melee attacks, but not between two Battle Axes.
