### ISSUE TITLE
Fully charged shield vibration and sound keeps playing until the next round

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#141]
If a round ends while a player has a fully charged Juice shield, he will notice the sound and vibration triggered by the fully charged shield will continue being triggered until the start of the next round.

**Comment by symbol24** [comment]
I did a quick audio fix for round ends, but vibrations will need to be looked at by victor.

**Comment by BenGoulet** [comment]
Since the sounds immediately end as soon as a player wins, this causes the explosion sound to not play.

Suggested fix: Add 1-2 seconds after a round ends before the round end screen appears.

**Comment by monstervictor** [comment]
Vibrations now stop on pause + end of round

**Comment by BenGoulet** [comment]
Still occurs if the WINNER of the round is a player that had the fully charged juice shield.

**Comment by monstervictor** [comment]
This should be resolved after the fix of https://github.com/symbol24/ProjectJuice/issues/152

**Comment by BenGoulet** [comment]
Fixed.
