### ISSUE TITLE
'Ground dash metal SFX' keeps resetting whenever I pull the next day

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#143]
In the Database Object, it must be the 3rd or 4th time that I have to go back and set the correct sound for 'Ground dash metal SFX', since it keeps resetting to 'Laser1' when I pull a version the next day.

Could there be something in the code that automatically resets it to that sound?

![grind_dash_sound](https://cloud.githubusercontent.com/assets/10607010/11051436/5188497e-871d-11e5-9631-1f01d5896e13.png)

**Comment by symbol24** [comment]
Just make sure that all info is pushed, IE database, soundmanger and the actual sounf clip, somewhere something got lost. my system resets the entry to the default (laser1) when it cant find the sound.

**Comment by jeffcerto** [comment]
seems to be fixed when last pulled
