### ISSUE TITLE
Shooting the opponent right under or right over him wont make the bullets hit opponent

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#144]
![image](https://cloud.githubusercontent.com/assets/11168751/11051425/3ac13e58-871d-11e5-9fc7-e216cbe40543.png)
![image](https://cloud.githubusercontent.com/assets/11168751/11051451/691a1108-871d-11e5-809a-58c63541e9d5.png)

**Comment by symbol24** [comment]
this was caused by the same issue that caused the juice to be hard to pick up.

**Comment by jeffcerto** [comment]
checked and fixed
