### ISSUE TITLE
Press pause once, the blue box will appear. unpause and press pause again, and the blue box wont appear

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#146]
you can still click which ever one you want, but its not as appealing for the eye

![image](https://cloud.githubusercontent.com/assets/11168751/11051796/37a369c8-8720-11e5-93b9-2fc56c8d1b35.png)
![image](https://cloud.githubusercontent.com/assets/11168751/11051799/443dbf76-8720-11e5-9d2a-aaad9379989f.png)

**Comment by symbol24** [comment]
this is something to do wit unity canvas, im not sure how to fix this, we'll see.

**Comment by symbol24** [comment]
found a fix, annoying but works now

**Comment by BenGoulet** [comment]
Fixed.
