### ISSUE TITLE
Overkilling someone using the Shield special shotgun attack causes a Draw Results screen and other issues

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#149]
When the player uses the Juice Shield's special shotgun attack in close range to kill the last opposing player, he will often notice that the Round Results screen will mention that the result was a draw, although it gives the victory to the correct player. Note that this causes a small slowdown to the game.

Moreover, this seems to trigger another issue:
- The music for the action phase will begin playing in the Round Results screen. Once the Round Results screen is skipped, the round results music will play instead.

**Comment by monstervictor** [comment]
TODO: Dying triggers multiple times, It needs to be reduced to a single time

**Comment by BenGoulet** [comment]
Note: We've managed to reproduce this without using the Shield special attack.

**Comment by symbol24** [comment]
we were spawning too much juice lol. limiting the juice spawned fixed this,. affects all but yeah, mainly the shield shotgun blast caused the issue more often.

**Comment by BenGoulet** [comment]
Seems fixed now. Tried two point blank fully charged shotgun blasts.
