### ISSUE TITLE
Holding the dart button doesn't stick to the other player

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#15]
Holding the dart button should stick to the player and continuing sucking his juice out, but it doesn't

**Comment by monstervictor** [comment]
New syphon gun added. It is responsive to the the special button. It will disappear when the button is release.

**Comment by BenGoulet** [comment]
The dart does not stick the other player and instead remains floating in the air at the point where it made contact. It still sucks our Juice during that time, however.

**Comment by monstervictor** [comment]
It follows the player and sticks to it now.

**Comment by jeffcerto** [comment]
checked and fixed
