### ISSUE TITLE
Once the game is build and loaded, yes the spawners are randomized, but once randomized it will always be at the same spawn point

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#150]
Example: the green is top left, and that player will always spawn on the top left

![image](https://cloud.githubusercontent.com/assets/11168751/11107621/aa759cda-88ad-11e5-814c-c6fa9fafa9c5.png)

**Comment by symbol24** [comment]
im going to have to refactor that whole random system :(

**Comment by symbol24** [comment]
the randomize spawn bool now randomizes the order of the spawn locations in script, and also changes between each round

**Comment by jeffcerto** [comment]
checked and fixed
