### ISSUE TITLE
Players' dont always controller the right robot

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#151]
the loadouts the players had selected will be swapped on load some times.

Ex:
Player A selects OBleak and the Battle Axe.
Player B selects TNT and the Juice Shield.

The game begins:
Player B controls OBleak and the Battle Axe.
Player A controls TNT and the Juice Shield.

**Comment by symbol24** [comment]
removed the randomizing of the player datas and moved it to spawn point locations.

**Comment by jeffcerto** [comment]
checked and fixed

**Comment by BenGoulet** [comment]
Actually still occurs; if Player A picks, for example, green and Player B picks purple, it is likely that, once in-game, Player A will control purple and Player B will control green.

**Comment by symbol24** [comment]
reopened and updated. the randomize has nothing to do with this. but i suspect its unty gamepad shenanigans.

**Comment by monstervictor** [comment]
It turned out that the bug was because we were using 2 different libraries for menus and player controls.
now we are using Windows libraries (XInput) only.

**Comment by BenGoulet** [comment]
This has not been reproduced after playing some time.
