### ISSUE TITLE
Dashing into a bullet often causes more damage than it should

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#158]
If a full health Player dashes into a triple bullet burst of an assault rifle, he will almost always die, even though the total damage of the three bullets is not enough to kill.

It could possibly be due to the bullet going so fast through the body of the maimframe that it hits the weak spot in the back, or that it somehow delivers its damage twice.

**Comment by symbol24** [comment]
yup thats exactly why its doing that, not much we ca do at this point... wnf
