### ISSUE TITLE
Explosion collider in crates prefab makes bullets invisible

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#16]
While shooting the explosion collider in the crate prefab, if the bullet hits the collider, the bullets go invisible.

![image](https://cloud.githubusercontent.com/assets/11168751/10090207/aaf3a978-62fa-11e5-96f3-70414f9a0c6f.png)

**Comment by jeffcerto** [comment]
Crates block all bullets. <--- for now it goes right through

**Comment by jeffcerto** [comment]
Pushing a crate slows the character down, since it is heavy. <--- doesnt slow down for now

**Comment by jeffcerto** [comment]
Sometimes if the player is over a barrel, he will get stuck

**Comment by jeffcerto** [comment]
When hit by a crate or barrel, the player gets damaged A LOT

**Comment by jeffcerto** [comment]
Particles after the exploaded barrel/crates : the player shouldnt be able to interact with them

**Comment by jeffcerto** [comment]
sometimes the player goes through the crate/barrel

**Comment by jeffcerto** [comment]
Now same thing with the sapping wire

**Comment by symbol24** [comment]
dart no longer disappears super early, but since our bullets move to fast it has the same behavior visually as walls, but you can see it hitting the crate as it explodes.

**Comment by BenGoulet** [comment]
Fixed.
