### ISSUE TITLE
No vibrations :(

### ISSUE THREAD

**Issue by symbol24** [symbol24/ProjectJuice#160]
Victor the change you added at the end thursday to the player vibration to prioritize the larger vibrations causes a nice null, so I added a null check but now theres no vibration at all.

I added a null check on _seetingsOnGoing, but that seems to have stopped vibrations completly. when its not there it gives a null pointer reference on _settingsOnGoing, anf it breaks gameply...

**Comment by BenGoulet** [comment]
Vibrations are back~
