### ISSUE TITLE
Player can get stuck in Pause Menu if he closes it as soon as it drops down

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#163]
This issue only occurs with specific timing and could only be reproduced in an .exe build.

If the player presses the Start or B Button to close the Pause Menu at the precise moment where the Pause screen is done moving down, it will raise back up and the game will never unpause, causing the players to become stuck.

**Comment by symbol24** [comment]
And this is prio 1? timing specific?

**Comment by BenGoulet** [comment]
I hesitated between 1 & 2, but considering it forces you to reboot the game and it happens by doing something that really isn't that far-fetched (pausing and unpausing quickly), I went with Prio 1.

One of those things that could hurt our final evaluation if Kevin happens to get it.

**Comment by BenGoulet** [comment]
I could not reproduce it on my end.
We'll have to hope the computers we demo the game on are fast enough : P

**Comment by BenGoulet** [comment]
Victor reproduced it and we were able to see some debug information. Maybe we can fix it?

**Comment by monstervictor** [comment]
We added a timer of 2 seconds (configurable) in case it happens.

**Comment by BenGoulet** [comment]
Could not reproduce so far.
