### ISSUE TITLE
The current Sapping Wire script does not have a sound for the wire snapping

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#165]
From what I can see, the new Dart Gun V2 script does not have a dropdown to select the sound for when the wire snaps anymore.

**Comment by monstervictor** [comment]
Added sound for wire snap

**Comment by BenGoulet** [comment]
You did!

**Comment by BenGoulet** [comment]
I'll re-close when Phil fixes the Laser1 issue where I can't keep the sound selected.

**Comment by BenGoulet** [comment]
There we go.
