### ISSUE TITLE
An aerial Battle Axe attack will deal the grounded Battle Axe damage if the player lands while doing it

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#166]
The Aerial Battle Axe damage was lowered to 50 due to it being too easy to pull off for a one-hit kill, while the Grounded Battle Axe damage remains at 100.

However, if the player starts an Aerial Battle Axe attack soon before landing on the ground, it will deal the full Grounded Battle Axe damage instead. This is rather easy to do, so I feel this would occur often in the course of a match.

**Comment by jeffcerto** [comment]
checked and fixed
