### ISSUE TITLE
Looping sounds will keep playing in the Pause Menu

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#167]
When the sounds of either the fully charged shield, or the sapping wire rewinding are currently playing, the player will notice they will play indefinitely if he pauses the game.

**Comment by symbol24** [comment]
should be fixed, if either of them is not fixed, please enter a bug for each seperatly as they are not handles the same way, thx.

**Comment by BenGoulet** [comment]
Both are fixed.
