### ISSUE TITLE
Looping Sapping Wire cooldown sound will keep playing in the Round End Menu and after

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#168]
This seems like it could only occur when two players have the Sapping Wire ability.

If the round ends before the sound of the Sapping Wire rewinding has completely stopped playing, it will keep looping in the Round end menu, and never stops playing, even into the next rounds.

**Comment by symbol24** [comment]
should be fixed

**Comment by BenGoulet** [comment]
Seems like the sound stops no matter the situation, so it looks fixed.
