### ISSUE TITLE
Returning to main menu from the pause screen, there is a period where players can still play.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#169]
If you pressed return to menu, you have a second to move your character however you want. If you move the character and make a vibration with the controller, that vibration will be brought with you to the main menu until you restart a new game.

**Comment by symbol24** [comment]
updated because jeff wrote 2 bugs with the same title bug had different meanings

**Comment by BenGoulet** [comment]
Could not move when going back to main menu.
