### ISSUE TITLE
Pressing the special ability button while in the air doesn't initiates a slow spinning attack with the war axe.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#17]
![image](https://cloud.githubusercontent.com/assets/11168751/10090235/061ed2be-62fb-11e5-8a19-24d63208d2ca.png)

**Comment by jeffcerto** [comment]
The grounded melee attack takes one second to become active, once the button is

pressed, the player can no longer turn around. <--- still hasnt been implemented

**Comment by symbol24** [comment]
added a dash down on aerial battleaxe and i make the axe appear the feet, and make the player sta in spot just an instant, this is only until we get the anims and stuff. It can be turned on off at the moment.

but the spinning is 100% anim driven, so thats not code ^^

**Comment by symbol24** [comment]
It does NOW! and we can set if the aerial is cancelled on land or not. its a slow massive thing!

**Comment by jeffcerto** [comment]
Checked and Fixed.
