### ISSUE TITLE
Battle keeps looping and cant be stopped

### ISSUE THREAD

**Issue by symbol24** [symbol24/ProjectJuice#172]
rar, but sometimes the battle axe appears to continue animating and looping, once its consumed it no longer is damaging.

**Comment by monstervictor** [comment]
Theoretically Fixed (Thanks symbol24*)

**Comment by monstervictor** [comment]
finally! 🥇 :)

**Comment by BenGoulet** [comment]
Lol you what

**Comment by symbol24** [comment]
Git hub had this still open from our final project and it was annoying me.
So I closed it xD
