### ISSUE TITLE
Getting stuck in the platform while jumping towards it

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#2]
https://www.youtube.com/watch?v=Z47qz9EObhY&feature=youtu.be

**Comment by jeffcerto** [comment]
Dashing towards the left it only rotates 180 degrees.
Dashing towards the right rotates fully 260 degrees
https://www.youtube.com/watch?v=7c5AfFy15rY

**Comment by symbol24** [comment]
This is fixed yay! \o/

**Comment by jeffcerto** [comment]
\o/

**Comment by BenGoulet** [comment]
Fixed.
