### ISSUE TITLE
Juice doesn't spray in the right way while getting melee'd

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#21]
Sometimes it will be shot towards the left or the right

![image](https://cloud.githubusercontent.com/assets/11168751/10090274/b3b4c956-62fb-11e5-8e1f-a0fc2a8adb5e.png)

**Comment by symbol24** [comment]
Ok, what do we want, do we want the juice to go towards the player that just did the melee, or does it go behind the guy that was meleed?

**Comment by BenGoulet** [comment]
If we're going to follow the design you pushed for regarding melee Juice:

When shot: The Juice will spray in the direction the player has been hit from with moderate to
high force.

When hit with a melee attack: The Juice will spray in the opposite direction the player has been hit from with moderate to high force. (if hit from the front, the Juice will spray from his back)

**Comment by symbol24** [comment]
fixed, but there is an issue that is art dependant where if you are hit from the melee on the opposite side from which the  attacking player is, the juice will be inverted. ocne we have actual art animations for melee we can get a second look.
