### ISSUE TITLE
Juice is sometimes stuck in the walls or floors, and is unreachable by the player.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#25]
Sometime the "juice" is stuck in the walls of floors, and it is unreachable by the player

![image](https://cloud.githubusercontent.com/assets/11168751/10090298/ec7671ae-62fb-11e5-8b21-81aacafa8264.png)

**Comment by symbol24** [comment]
fixed sunday

**Comment by jeffcerto** [comment]
Happened today while exploading one of the barrels

![image](https://cloud.githubusercontent.com/assets/11168751/10925800/53bccdf4-825f-11e5-812e-19693c3faa00.png)

**Comment by symbol24** [comment]
This doesnt happen alot anymore, but its not something that we can fix easily, time versus value makes this a wnf
