### ISSUE TITLE
Player gets stuck while being on top of the crate prefab.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#26]
Sometimes if the player is over a crate, he will get stuck

**Comment by symbol24** [comment]
Fixed submitted

**Comment by symbol24** [comment]
Can I get a screenshot please?

**Comment by jeffcerto** [comment]
So when the player is on top of the crate, he cant jump and he can only move left or right. He can also dash but if he dashes upwards, now he will become really stuck and cant do anything after

![image](https://cloud.githubusercontent.com/assets/11168751/10119563/92391616-6467-11e5-9ed7-c2d0df19854e.png)

**Comment by BenGoulet** [comment]
Still occurs according to Jeffaroni

**Comment by symbol24** [comment]
fixed, submit coming
