### ISSUE TITLE
When the player get hit by the crate collision, it takes way too much damage

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#27]
When hit by a crate or barrel, the player gets damaged A LOT

![image](https://cloud.githubusercontent.com/assets/11168751/10090312/1760b58c-62fc-11e5-8ca0-d1a35c00db6c.png)

**Comment by monstervictor** [comment]
Made the explosion last only one frame. That should solve the issue.

**Comment by BenGoulet** [comment]
Fixed.
