### ISSUE TITLE
Missing feedback when able to fire Assault Rifle 

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#31]
For the prototype next week, Kevin has requested that we have better feedback for when the player can shoot his rifle again. These are my suggestions:

Effect: The player's rifle flashes white rapidly twice to indicate that it can be fired again.
Vibration: A weak, short vibration when the player can fire again. (optional)

**Comment by jeffcerto** [comment]
yea sure I dig that

**Comment by symbol24** [comment]
A white flashes around the player, can set the amount of times and the time it flashes and in between. have at it!

**Comment by BenGoulet** [comment]
Fixed.
