### ISSUE TITLE
Missing feedback when able to melee attack

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#32]
For the prototype next week, Kevin has requested that we have better feedback for when the player can melee again. These are my suggestions:
- Effect: The whole character sprite flashes white twice when the cooldown has ended.
- Vibration: A weak, short vibration when the player can melee again (optional)
- Sound Effect: A sound of a knife being sheathed is played after the melee attack. The player can melee again at the end of this sound.(optional)

**Comment by symbol24** [comment]
A white flashes around the player, can set the amount of times and the time it flashes and in between. have at it!

**Comment by BenGoulet** [comment]
Fixed.
