### ISSUE TITLE
Juice doesn't come out at the right place while player is getting shot by bullets

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#34]
![image](https://cloud.githubusercontent.com/assets/11168751/10089975/be86b67c-62f7-11e5-9541-0ac1a19fa470.png)

**Comment by monstervictor** [comment]
The problem seems to have fixed itself with the slower bullets

**Comment by monstervictor** [comment]
Reworked the math and made particles spawn in more precise locations. Not Pushed yet
