### ISSUE TITLE
When pausing the game, the players gun position is reset

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#38]
When you press the pause button, if the player had his gun pointing in any direction, the gun will be reset to the 90 degree angle.

![deleting](https://cloud.githubusercontent.com/assets/11168751/10118838/7b4f0124-6451-11e5-9ce6-d63deda3548b.gif)

**Comment by symbol24** [comment]
The aiming is being flushed, as is all inputs, this is to prevent the animations we were getting and stuff like that. Once the pause menu is removed the aiming will automatically reposition itself with the stick input.

I say we can live with this.

**Comment by BenGoulet** [comment]
Actually fixed now. \o/
