### ISSUE TITLE
Round Results: Screen can become stuck if a player buffers A or B Button input when round ends

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#41]
If the player presses the A or B Button at the right time when the round ends, just as the Round Results screen would appear, he will notice the screen will remain visible while the next round begins. There is no way for the players to make it vanish until the next round.

**Comment by jeffcerto** [comment]
checked and fixed

**Comment by BenGoulet** [comment]
Reopened: We managed to reproduce it during the proto demo with Osama, didn't we, Phil?

**Comment by symbol24** [comment]
the reproduce is due to insane lag we got because a bug victor has to fix.

**Comment by symbol24** [comment]
havent see it in a while

**Comment by jeffcerto** [comment]
seems to not do it anymore
