### ISSUE TITLE
Whenever the player is hugging a vertical wall, he is able to hit enemies on the other side of it

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#46]
When the player is touching a vertical wall and facing it, he will notice that all hit boxes will go through it:
- Bullets can be shot through
- Melee attacks can be performed through them
- The sapping wire can be shot through them
- The bullets shot from the shield go through them.

**Comment by symbol24** [comment]
this will be fixed once we have proper models for art.
- shooting: the bullets appear at the tip of the gun, so if the tip is on the other side of a wall, it spawns there.
- Melee is a debug for now, once we have an animation we can check if we are hitting a wall and cancel the melee.(or something)
- Sapping uses the same spawn point as the bullets.
- Shield bullets as well.

**Comment by BenGoulet** [comment]
Our level doesn't have a spot where this is possible.
