### ISSUE TITLE
Juice Shield: Shield does not stop the Sapping Dart

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#48]
When the Sapping Dart hits a player's Shield, the shield will not block it.

**Comment by monstervictor** [comment]
Changed the dart script to look for ShieldReRouter + added trigger collider to the shield.

**Comment by jeffcerto** [comment]
Checked and fixed, but if player is already sucking juice from the other player and now the other player presses the shield, it wont cut the wire of the sapping wire

**Comment by symbol24** [comment]
Please enter a new issue for the new behavior, its easier to keep track as the sumamry no longer represent the issue.

**Comment by jeffcerto** [comment]
With shield 2.0, the player is able to suck through the shield

**Comment by symbol24** [comment]
fixed 2.0

**Comment by BenGoulet** [comment]
Reopened: The issue seems to be with the Sapping Dart itself, which is so fast it sometimes goes through the Shield and saps the player's life anyway.

**Comment by monstervictor** [comment]
Check if this still happens

**Comment by BenGoulet** [comment]
Fixed.
