### ISSUE TITLE
If dart is used to deplete the opponent HP, and the opponent HP hits 0, It causes a draw

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#50]

**Comment by BenGoulet** [comment]
Note the actual steps are not yet known, as performing the same steps can also lead to a regular victory.

**Comment by monstervictor** [comment]
Temporary fix for the prototype. It turns out to be the DartHose and Dart when they are destroyed

**Comment by monstervictor** [comment]
This issue seems to not happen after fixing issue #69 :

**Comment by jeffcerto** [comment]
checked and fixed
