### ISSUE TITLE
Juice that hasnt been collected yet stays after a new round begins

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#52]

**Comment by symbol24** [comment]
I had confirmed with Benjamin last week that this was the design.

**Comment by BenGoulet** [comment]
I can believe I said that for the not respawning crate (and if I did, I regret it now), but are you guys really okay with grabbable Juice just laying around after a round to get gathered?

Although the more I think about it, the less bad that seems.

**Comment by symbol24** [comment]
I really like the idea of a persistent battle arena. we can have a system where we can spawn maybe a few crates, i am not against the idea, but i like the idea of the debris remaining.
