### ISSUE TITLE
At the end of a round screen, the animations of the player are still going.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#54]
The player animations have to be turned off at the round result screen

![image](https://cloud.githubusercontent.com/assets/11168751/10181879/99a9eaf2-66eb-11e5-8ae8-eafe59fac0be.png)

**Comment by symbol24** [comment]
I am flushing the controller inputs and the anim state now, this should be fixed.

**Comment by BenGoulet** [comment]
Fixed. Character cannot be controlled once the round results screen appears.
