### ISSUE TITLE
Sapping Wire: Cannot be shot down from pass-through platforms

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#58]
When the player is standing on a pass-through platform and shoots the Sapping Wire down, he will notice the wire will be blocked by the platform.

Just like bullets, it would be expected for the wire to be able to go through these platforms from any angle.

**Comment by monstervictor** [comment]
It should be fixed. There might be issues with the edges though.

**Comment by jeffcerto** [comment]
checked and fixed
