### ISSUE TITLE
Sapping Wire: There is no cooldown on the Sapping Wire

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#60]
When the player lets go of the button to fire the Sapping Wire, he is immediately able to fire it again. There should be a setting to add/lessen cooldown between shots.

**Comment by monstervictor** [comment]
Added cooldown from the moment that the dart is destroyed. The property is defaulted to 0.5sec. Changes will be pushed soon

**Comment by monstervictor** [comment]
![dartgun](https://cloud.githubusercontent.com/assets/3688151/10381874/5aca6700-6dec-11e5-8176-515027684e8b.PNG)
Cooldown is added.

**Comment by jeffcerto** [comment]
checked and fixed
