### ISSUE TITLE
Player keeps colliding with the sides of pass-through platforms

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#62]
When navigating the map, players will constantly and easily collide with the left and right sides of the pass-through platforms.

![platform_sides](https://cloud.githubusercontent.com/assets/10607010/10237668/a7fb2ee8-6882-11e5-8e21-f0e92204ebb8.png)

**Comment by symbol24** [comment]
Making the sides of the platforms pass through requires ANOTHER complete overhaul of the system. which i wont do.

Comparing to other platformers that have pass through platforms, passing through on the sides is not a comon thing, and it most of the times feels like a bug.

WNF.

**Comment by BenGoulet** [comment]
I'll remind myself to drop a word about this to Luc. I think it's one of our main issues and I'd love to know if there's an easy way to fix it we don't know about.
