### ISSUE TITLE
While pushing the crate prefab, sometimes it wont be pushed off the ledge

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#63]

**Comment by monstervictor** [comment]
Added circular colliders to the 4 corners. made the box collider smaller and it passes through the ledge now.

![capture](https://cloud.githubusercontent.com/assets/3688151/10297711/bbf3a1b2-6ba4-11e5-8d6b-9033208bfef6.PNG)
Colliders will change when the real assets are in the game object

**Comment by jeffcerto** [comment]
checked and fixed
