### ISSUE TITLE
Explosion from Explosive Barrels is always full damage

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#64]
According to the GDD:

"When explosive barrels break, they explode and deal damage in a circular radius around them, as well as create a blast that pushes players and barrels/crates in the way."

Currently, if the explosion does damage, it will always be the maximum damage and auto-kill the player.

**Comment by monstervictor** [comment]
This has been changed, but not yet pushed. Now Damaging objects (whichever has impact settings) can add distance mitigation.

**Comment by monstervictor** [comment]
![fadedmgondistance](https://cloud.githubusercontent.com/assets/3688151/10325968/f7d0fabc-6c63-11e5-9f00-6806c054e678.png)
Removed damage factor for being useless. The script assumes that at the max distance damage is 0, at distance 0, the damage is maximum and calculates the ratio according to that

**Comment by jeffcerto** [comment]
checked and fixed
