### ISSUE TITLE
Round result : every team scores should start at the same place

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#66]
![fuckyou](https://cloud.githubusercontent.com/assets/11168751/10325916/7d96ee32-6c63-11e5-9bfd-c40614e0f5d0.png)

**Comment by jeffcerto** [comment]
![image](https://cloud.githubusercontent.com/assets/11168751/10325900/5d015e64-6c63-11e5-9364-9acada08272b.png)

**Comment by symbol24** [comment]
This will be fixed once I create the actual art

**Comment by jeffcerto** [comment]
checked and fixed
