### ISSUE TITLE
Each bullet doesn't apply a force to whatever they hit.

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#7]
In the game, each bullet applies a force to whatever they hit, which can knock objects over, or push

opponents away. It does not apply force to the player or the crates so far in our build

![image](https://cloud.githubusercontent.com/assets/11168751/10090027/5c18ffa8-62f8-11e5-896b-db78f63de72a.png)

**Comment by symbol24** [comment]
fixed bullets so they properly do knockback on both players and crates

**Comment by jeffcerto** [comment]
checked and fixed
