### ISSUE TITLE
When you shoot the dart too close to a player, and it hits, the dart disappears but still sucks

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#72]
![image](https://cloud.githubusercontent.com/assets/11168751/10381955/fb956f68-6dec-11e5-8230-f18d53eb3aec.png)

**Comment by BenGoulet** [comment]
Waiting on https://github.com/symbol24/ProjectJuice/issues/132 to be fixed before closing this, but it looks fixed.

**Comment by BenGoulet** [comment]
The dart doesn't suck anymore in this situation.
