### ISSUE TITLE
Players can pick the same Hydroil

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#77]
![image](https://cloud.githubusercontent.com/assets/11168751/10471118/b8d6fd2a-71e0-11e5-9caf-66564726a284.png)

**Comment by BenGoulet** [comment]
Isn't this timing dependent? I remember being able to do this when I pressed A really fast in the character select.

**Comment by jeffcerto** [comment]
no still happens in the build and its not timing dependent

**Comment by jeffcerto** [comment]
Until the player hasn't confirmed his logo, the other player can still access it.

**Comment by symbol24** [comment]
Sponsor is "locked in" the first time you press A, with taht, i could not reproduce the issue of more than 1person taking the same sponsor.

**Comment by jeffcerto** [comment]
checked and fixed
