### ISSUE TITLE
Adding a timer before the end of each round

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#80]
When only one player remains at the end of a round, the round end screen will immediately appear.

This causes the round end screen's sounds to overlap with whatever sounds were playing at the moment of the round's end, in addition to feeling too fast/abrupt.

There could be a small timer of 1-2 seconds at the end of each round.

**Comment by symbol24** [comment]
![delayalreadyexists](https://cloud.githubusercontent.com/assets/9352028/10549371/b43602d6-740e-11e5-9dd1-bd41c5d8e942.jpg)

**Comment by symbol24** [comment]
this already existed, you just need to set the time you want.

**Comment by BenGoulet** [comment]
Fixed.
