### ISSUE TITLE
Shooting the shotgun blast of the fully charged Shield requires player to hold the button

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#83]
When the player has the Juice Shield and wants to activate it, he needs to hold the button down.

However, when he has the fully charged shield and wants to fire the stored bullets, he will notice he will still need to hold the button down for a bit; the intended design is for the shotgun blast to be immediately fired.

**Comment by symbol24** [comment]
fixed

**Comment by BenGoulet** [comment]
Fixed.
