### ISSUE TITLE
Sound when going back to character select from Match Results screen does not play

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#85]
(If it's a sound I can't find in Unity, let me know where it is)

When the player pauses the game and quits back to Main Menu, he will hear a sound of a screen turning off.

However, when he reaches the Match Results screen, he will notice that quitting back to the Character Select screen will not play this sound,

**Comment by symbol24** [comment]
ferxeded

**Comment by BenGoulet** [comment]
Hmm you can explain to me how I somehow messed up, but it is still not playing on my end.

**Comment by symbol24** [comment]
je viens de lessayer ca marche :/

**Comment by symbol24** [comment]
ok now its fixed

**Comment by BenGoulet** [comment]
Fixed.
