### ISSUE TITLE
Aerial Battle Axe sound keeps playing when the player lands

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#87]
If the player uses the Battle Axe in the air, he will notice the whooshing sound that plays for the Aerial Battle Axe will keep playing when he lands on the ground.

**Comment by symbol24** [comment]
You audio file is a double woosh, is that what you mean? cause it only plays the audio once, and it is a double woosh.

**Comment by BenGoulet** [comment]
I could "fix" it by making the sound a single whoosh, but if, say, I start the aerial attack right before landing on the ground, it'll still play the whole audio file.

Hmm is there a way to call something "on touch ground"? Like, stop the sound once player touches ground.

**Comment by symbol24** [comment]
I added an option on melee that sets if you want to have the landing cancel aerial melee ability.

**Comment by jeffcerto** [comment]
Checked and Fixed.
