### ISSUE TITLE
Missing Star animation on round winning

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#88]
(I know it's not ready yet, I'm entering this as a reminder for us)

When a round ends, the winner of the round will receive a medal.
There is currently no sound attributed to this event in Unity.

**Comment by symbol24** [comment]
In the round menu script there is a Medal Appear SFX...

**Comment by BenGoulet** [comment]
I'll have another look, I literally based this bug off of you saying it didn't exist yet lol

**Comment by symbol24** [comment]
The sound is there, its just being used yet as there is no animation for the gain a medal.

**Comment by BenGoulet** [comment]
I removed the CNR label since the last comment suggests the issue is waiting to be fixed.

**Comment by symbol24** [comment]
FIXED! You can play around with the timing and amount of flashes to fit the sound.
![stars](https://cloud.githubusercontent.com/assets/9352028/11106159/e0b7ed72-88a1-11e5-8fd5-dbc90b138160.png)

**Comment by jeffcerto** [comment]
checked and fixed
it fits with the animationes
