### ISSUE TITLE
Pause: Player only returns to the character select screen after unpausing the game

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#89]
When the player pauses the game and chooses to return to the Character Select screen, he will notice the sound to return to the Character Select screen will play, but nothing will actually happen.

The character select screen will only actually load when the player returns to the gameplay, after about a second.

**Comment by symbol24** [comment]
I fixed my timer logic, sorry,

In the pause menu script there is a Delay to return, this is the time you set to return to the player select screen, it is currently set to 2 seconds.

**Comment by BenGoulet** [comment]
It looks like it works, but I land on a black screen; I'll recheck this Monday when I can build & run with 2 controllers.

**Comment by BenGoulet** [comment]
Phil says it's k.
