### ISSUE TITLE
Character Select: Players unable to select the same corporation more than once without rebooting

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#90]
Once the players reach the gameplay phase with certain corporations (Human Hydroil and Hydroil + for example), he will notice that the next time he reaches the Character Select screen, these same corporations will now be impossible to select.

This effect even tallies, which will eventually cause the players to be unable to pick any corporation.

![cant_select_corp](https://cloud.githubusercontent.com/assets/10607010/10555442/76a8ceb0-743d-11e5-8d2c-a72126b12e33.png)

**Comment by jeffcerto** [comment]
checked and fixed
