### ISSUE TITLE
Shooting the shotgun blast of the fully charged Shield also allows player to immediately put up Shield

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#91]
When the player has a fully charged Juice Shield and fires the shotgun blast, he will notice that if he holds down the Special Ability button, he will also be able to activate the shield at the same time.

It would be expected for the shotgun blast to be the player's only action, followed by the usual cooldown time before he can put the shield back up again.

**Comment by symbol24** [comment]
arg, this was the design, dont enter these as straight up bugs... im also on the fence, i like the way it is now.

**Comment by BenGoulet** [comment]
"Once fully charged, your character changes color (contrast), to release the bullets : press the same button to use the shield (RB), it does not need to be held for this."

I guess this is the line that threw you off? I can see how you could read it as "you can use the shotgun and use shield right after", though, so my bad.

I guess we can keep it as is for now and see if it's OP.
