### ISSUE TITLE
Rounds sometime end in Draws, can trigger broken Match Results screen

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#92]
More time needed to isolate the issue, might be related to overkilling an opponent.

The user will sometimes notice the round ending will show that the 'Winner is Draw' even though one player clearly remained alive.

If this occurs on the last round of a match, this can lead to a broken Match Ending with three different buttons and the left joystick will stop responding.

Jeff seems to easily reproduce it, so it may also be caused by slow performance.
Will add more details if found.

![round_draw_final_round](https://cloud.githubusercontent.com/assets/10607010/10555890/8ae39c50-7444-11e5-8cb2-0aabdea34db1.png)

**Comment by BenGoulet** [comment]
Will need to make sure this doesn't happen anymore.

**Comment by jeffcerto** [comment]
checked and it doesnt happen often
