### ISSUE TITLE
Recently lost Juice not shown in white in Health Bar

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#95]
The recently depleted Juice the player has just lost by being hit should be shown in white in the Health Bar before disappearing, as seen in Feedback document:

When the player takes damage, the amount of Juice he has lost is shown in white. If he does not take damage for 2 seconds, the white depletes. The depleted Juice no longer appears as a neon color on the robot's side.

![white_bar](https://cloud.githubusercontent.com/assets/10607010/10595079/059d7600-76a2-11e5-9993-e3ff58305af5.png)

**Comment by monstervictor** [comment]
This has been implemented, but we are struggling to update the player. It will soon be integrated

**Comment by BenGoulet** [comment]
Fixed.
