### ISSUE TITLE
There should be a sound when collecting Juice on the ground

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#98]
(Added to Feedback Document, Player Health Tab)

When the player walks over Juice laying on the ground, a sound should be triggerable to give feedback to the player that he is getting health back.

This should should not play 15 times if the player picks up 15 pieces of Juice at the same time but instead play once, finish, and then play again if the player continues picking up Juice.

OR

It could play up to X times within a second and no more, to prevent spamming it too much.

**Comment by symbol24** [comment]
sound selection can be found in the database object.

**Comment by jeffcerto** [comment]
checked and fixed
