### ISSUE TITLE
Destroyed Barrels and Crates should respawn after every round

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#99]
As agreed upon: We want destroyed crates and barrels to re-appear at the start of every round.
Debris from destroyed crates must stay though.

**Comment by monstervictor** [comment]
This has been implemented. They respawn in the same position every round. The positions are gotten at runtime (loading the scene)
You can move barrels/crates around the scene and do not need to change anything.

**Comment by jeffcerto** [comment]
checked and fixed
